/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calcolatrice;

/**
 *
 * @author giovanni.stevanato
 */
public class frame extends javax.swing.JFrame {

	/**
	 * Creates new form frame
	 */
	public frame() {
		initComponents();
		Espressione e;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schermo = new javax.swing.JTextField();
        sette = new javax.swing.JButton();
        quattro = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        virgola = new javax.swing.JButton();
        otto = new javax.swing.JButton();
        nove = new javax.swing.JButton();
        cinque = new javax.swing.JButton();
        sei = new javax.swing.JButton();
        due = new javax.swing.JButton();
        tre = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        uguale = new javax.swing.JButton();
        cancella = new javax.swing.JButton();
        elimina = new javax.swing.JButton();
        moltiplicazione = new javax.swing.JButton();
        divisione = new javax.swing.JButton();
        addizione = new javax.swing.JButton();
        sottrazione = new javax.swing.JButton();
        apri = new javax.swing.JButton();
        chiudi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        schermo.setEditable(false);

        sette.setText("7");
        sette.setMaximumSize(new java.awt.Dimension(40, 40));
        sette.setMinimumSize(new java.awt.Dimension(40, 40));
        sette.setPreferredSize(new java.awt.Dimension(40, 40));
        sette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setteActionPerformed(evt);
            }
        });

        quattro.setText("4");
        quattro.setMaximumSize(new java.awt.Dimension(40, 40));
        quattro.setMinimumSize(new java.awt.Dimension(40, 40));
        quattro.setPreferredSize(new java.awt.Dimension(40, 40));
        quattro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quattroActionPerformed(evt);
            }
        });

        uno.setText("1");
        uno.setMaximumSize(new java.awt.Dimension(40, 40));
        uno.setMinimumSize(new java.awt.Dimension(40, 40));
        uno.setPreferredSize(new java.awt.Dimension(40, 40));
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });

        virgola.setText(".");
        virgola.setMaximumSize(new java.awt.Dimension(40, 40));
        virgola.setMinimumSize(new java.awt.Dimension(40, 40));
        virgola.setPreferredSize(new java.awt.Dimension(40, 40));
        virgola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virgolaActionPerformed(evt);
            }
        });

        otto.setText("8");
        otto.setMaximumSize(new java.awt.Dimension(40, 40));
        otto.setMinimumSize(new java.awt.Dimension(40, 40));
        otto.setPreferredSize(new java.awt.Dimension(40, 40));
        otto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ottoActionPerformed(evt);
            }
        });

        nove.setText("9");
        nove.setMaximumSize(new java.awt.Dimension(40, 40));
        nove.setMinimumSize(new java.awt.Dimension(40, 40));
        nove.setPreferredSize(new java.awt.Dimension(40, 40));
        nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noveActionPerformed(evt);
            }
        });

        cinque.setText("5");
        cinque.setMaximumSize(new java.awt.Dimension(40, 40));
        cinque.setMinimumSize(new java.awt.Dimension(40, 40));
        cinque.setPreferredSize(new java.awt.Dimension(40, 40));
        cinque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinqueActionPerformed(evt);
            }
        });

        sei.setText("6");
        sei.setMaximumSize(new java.awt.Dimension(40, 40));
        sei.setMinimumSize(new java.awt.Dimension(40, 40));
        sei.setPreferredSize(new java.awt.Dimension(40, 40));
        sei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seiActionPerformed(evt);
            }
        });

        due.setText("2");
        due.setMaximumSize(new java.awt.Dimension(40, 40));
        due.setMinimumSize(new java.awt.Dimension(40, 40));
        due.setPreferredSize(new java.awt.Dimension(40, 40));
        due.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dueActionPerformed(evt);
            }
        });

        tre.setText("3");
        tre.setMaximumSize(new java.awt.Dimension(40, 40));
        tre.setMinimumSize(new java.awt.Dimension(40, 40));
        tre.setPreferredSize(new java.awt.Dimension(40, 40));
        tre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treActionPerformed(evt);
            }
        });

        zero.setText("0");
        zero.setMaximumSize(new java.awt.Dimension(40, 40));
        zero.setMinimumSize(new java.awt.Dimension(40, 40));
        zero.setPreferredSize(new java.awt.Dimension(40, 40));
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        uguale.setText("=");
        uguale.setMaximumSize(new java.awt.Dimension(40, 40));
        uguale.setMinimumSize(new java.awt.Dimension(40, 40));
        uguale.setPreferredSize(new java.awt.Dimension(40, 40));
        uguale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugualeActionPerformed(evt);
            }
        });

        cancella.setText("C");
        cancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancellaActionPerformed(evt);
            }
        });

        elimina.setText("⇚");
        elimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaActionPerformed(evt);
            }
        });

        moltiplicazione.setText("*");
        moltiplicazione.setMaximumSize(new java.awt.Dimension(40, 23));
        moltiplicazione.setMinimumSize(new java.awt.Dimension(40, 23));
        moltiplicazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moltiplicazioneActionPerformed(evt);
            }
        });

        divisione.setText("/");
        divisione.setMaximumSize(new java.awt.Dimension(40, 23));
        divisione.setMinimumSize(new java.awt.Dimension(40, 23));
        divisione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisioneActionPerformed(evt);
            }
        });

        addizione.setText("+");
        addizione.setMaximumSize(new java.awt.Dimension(40, 23));
        addizione.setMinimumSize(new java.awt.Dimension(40, 23));
        addizione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addizioneActionPerformed(evt);
            }
        });

        sottrazione.setText("-");
        sottrazione.setMaximumSize(new java.awt.Dimension(40, 23));
        sottrazione.setMinimumSize(new java.awt.Dimension(40, 23));
        sottrazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sottrazioneActionPerformed(evt);
            }
        });

        apri.setText("(");
        apri.setMaximumSize(new java.awt.Dimension(1000, 10000));
        apri.setMinimumSize(new java.awt.Dimension(0, 0));
        apri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apriActionPerformed(evt);
            }
        });

        chiudi.setText(")");
        chiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiudiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(quattro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cinque, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sei, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(due, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sette, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(otto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nove, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(virgola, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uguale, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancella, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(elimina, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divisione, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moltiplicazione, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sottrazione, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addizione, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(schermo)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(apri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chiudi)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(schermo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nove, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(otto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sette, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quattro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cinque, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sei, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(due, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(virgola, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uguale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancella, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(elimina, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divisione, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moltiplicazione, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sottrazione, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addizione, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apri, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chiudi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setteActionPerformed
        schermo.setText(schermo.getText() + "7");
    }//GEN-LAST:event_setteActionPerformed

    private void ottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ottoActionPerformed
        schermo.setText(schermo.getText() + "8");
    }//GEN-LAST:event_ottoActionPerformed

    private void noveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noveActionPerformed
        schermo.setText(schermo.getText() + "9");
    }//GEN-LAST:event_noveActionPerformed

    private void quattroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quattroActionPerformed
        schermo.setText(schermo.getText() + "4");
    }//GEN-LAST:event_quattroActionPerformed

    private void cinqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinqueActionPerformed
        schermo.setText(schermo.getText() + "5");
    }//GEN-LAST:event_cinqueActionPerformed

    private void seiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seiActionPerformed
        schermo.setText(schermo.getText() + "6");
    }//GEN-LAST:event_seiActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        schermo.setText(schermo.getText() + "1");
    }//GEN-LAST:event_unoActionPerformed

    private void dueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dueActionPerformed
        schermo.setText(schermo.getText() + "2");
    }//GEN-LAST:event_dueActionPerformed

    private void treActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treActionPerformed
        schermo.setText(schermo.getText() + "3");
    }//GEN-LAST:event_treActionPerformed

    private void virgolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virgolaActionPerformed
        schermo.setText(schermo.getText() + ".");
    }//GEN-LAST:event_virgolaActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        schermo.setText(schermo.getText() + "0");
    }//GEN-LAST:event_zeroActionPerformed

    private void ugualeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugualeActionPerformed
        Espressione e = new Espressione(schermo.getText());
		schermo.setText(Double.toString(e.getRis()));
    }//GEN-LAST:event_ugualeActionPerformed

    private void cancellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancellaActionPerformed
        schermo.setText("");
    }//GEN-LAST:event_cancellaActionPerformed

    private void eliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaActionPerformed
        schermo.setText(schermo.getText().substring(0,schermo.getText().length()-1));
    }//GEN-LAST:event_eliminaActionPerformed

    private void divisioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisioneActionPerformed
        char c = schermo.getText().charAt(schermo.getText().length()-1);
		if((c!='+') && (c!='-') && (c!='*') && (c!='/') && (c!='.') && (c!='(')){
			schermo.setText(schermo.getText() + "/");
		}
    }//GEN-LAST:event_divisioneActionPerformed

    private void moltiplicazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moltiplicazioneActionPerformed
        char c = schermo.getText().charAt(schermo.getText().length()-1);
		if((c!='+') && (c!='-') && (c!='*') && (c!='/') && (c!='.') && (c!='(')){
			schermo.setText(schermo.getText() + "*");
		}
    }//GEN-LAST:event_moltiplicazioneActionPerformed

    private void sottrazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sottrazioneActionPerformed
        char c = schermo.getText().charAt(schermo.getText().length()-1);
		if((c!='+') && (c!='-') && (c!='*') && (c!='/') && (c!='.') && (c!='(')){
			schermo.setText(schermo.getText() + "-");
		}
    }//GEN-LAST:event_sottrazioneActionPerformed

    private void addizioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addizioneActionPerformed
        char c = schermo.getText().charAt(schermo.getText().length()-1);
		if((c!='+') && (c!='-') && (c!='*') && (c!='/') && (c!='.') && (c!='(')){
			schermo.setText(schermo.getText() + "+");
		}
    }//GEN-LAST:event_addizioneActionPerformed

    private void apriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apriActionPerformed
        schermo.setText(schermo.getText() + "(");
    }//GEN-LAST:event_apriActionPerformed

    private void chiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiudiActionPerformed
        schermo.setText(schermo.getText() + ")");
    }//GEN-LAST:event_chiudiActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new frame().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addizione;
    private javax.swing.JButton apri;
    private javax.swing.JButton cancella;
    private javax.swing.JButton chiudi;
    private javax.swing.JButton cinque;
    private javax.swing.JButton divisione;
    private javax.swing.JButton due;
    private javax.swing.JButton elimina;
    private javax.swing.JButton moltiplicazione;
    private javax.swing.JButton nove;
    private javax.swing.JButton otto;
    private javax.swing.JButton quattro;
    private javax.swing.JTextField schermo;
    private javax.swing.JButton sei;
    private javax.swing.JButton sette;
    private javax.swing.JButton sottrazione;
    private javax.swing.JButton tre;
    private javax.swing.JButton uguale;
    private javax.swing.JButton uno;
    private javax.swing.JButton virgola;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
